/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientews;


import com.fenoreste.webservice.impl.WsTDD;
import com.syc.ws.endpoint.siscoop.BalanceQueryResponseDto;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import javax.swing.JOptionPane;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 *
 * @author wilmer
 */
public class menuC extends javax.swing.JFrame {

    /**
     * Creates new form menuC
     */
    
 
    private WsTDD cajeroEmisor;
    
    private final String ip = "192.168.99.113"; 
    private final String puerto = "8181";
    
    public menuC() {
        initComponents();
        this.setLocationRelativeTo(null);
        if(conectaWsdl()){
            
        }else{
            System.exit(0);
        }
        //conectaWsdl();
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    
    private boolean conectaWsdl() {
        String patch = "https://" + ip + ":" + puerto;
        String urlCajeroEmisor = patch + "/WsTDDImplService/WsTDDImpl?wsdl";
        String q_name = "http://impl.webservice.fenoreste.com/";
        System.out.println(urlCajeroEmisor);
        try {
            URL urlcr = new URL(urlCajeroEmisor);
            if (pingURL(urlcr)) {
                QName siscoop_cr = new QName(q_name, "WsTDDImplService");
                Service servicecr = Service.create(urlcr, siscoop_cr);
                cajeroEmisor = servicecr.getPort(WsTDD.class);                
                return true;
            } else {
                 JOptionPane.showMessageDialog(null,"Error al conectar al web service","",JOptionPane.ERROR_MESSAGE);
                 return false;
            }
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, "Error al generar la URL del wsdl. \n" + ex.getMessage(), "ERROR CONEXION", JOptionPane.ERROR_MESSAGE);
              return false;
        }
    }

    private boolean pingURL(URL url) {
        try {
            System.out.println("Entro");
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            System.out.println("paso");
            connection.setConnectTimeout(2000);
            connection.setReadTimeout(2000);
            System.out.println("paso");
            int codigo = connection.getResponseCode();
            System.out.println("paso");
            System.out.println("Codigo:"+codigo);
            if (codigo == 200) {
                System.out.println("Ping exitoso");
                return true;
            }
        } catch (IOException | java.lang.RuntimeException ex) {
            System.out.println("Error:"+ex.getMessage());
            JOptionPane.showMessageDialog(null,"No hay respuesta de url:"+url,"",JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }
    
    private void consultarSaldoTDD() {
       try {
           BalanceQueryResponseDto saldo =cajeroEmisor.wsSaldoTDDReq(txtTarjeta.getText(),txtNip.getText());
           System.out.println("si:"+saldo.getDescription());
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR AL OBTENER SALDO:"+e.getMessage());
        }

    }
    
    private void retirarTDD(){
 
        String cuenta=txtTarjeta.getText();
        String monto=txtRetirar.getText();
        String idUsuario=txtNip.getText();
        System.out.println("Cuenta:"+cuenta+"\n monto:"+monto+"\n idusuario:"+idUsuario);
        try {
            boolean retiro=cajeroEmisor.wsRetiroTDDReq(cuenta,monto,idUsuario);
          }catch (Exception e) {
            
        }
        
    }
    
    private void DepositarTDD(){
       String cuenta=txtTarjeta.getText();
       String monto=txtRetirar.getText();
       String idUsuario=txtNip.getText();
       System.out.println("Cuenta:"+cuenta+"\n monto:"+monto+"\n idusuario:"+idUsuario);
       
        try {
            boolean deposito=cajeroEmisor.wsDepositoTDDReq(cuenta,monto,idUsuario);
        } catch (Exception e) {
        }
        
    }
      
      
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCambiarDetallesTDD = new javax.swing.JButton();
        internal_cajero = new javax.swing.JDesktopPane();
        btnConsultarTDD = new javax.swing.JButton();
        btnTranferirTDD = new javax.swing.JButton();
        btnRetirarTDD = new javax.swing.JButton();
        txtRetirar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        btnAsignarTDD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCambiarDetallesTDD.setText("CAMBIAR DETALLES");
        btnCambiarDetallesTDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarDetallesTDDActionPerformed(evt);
            }
        });

        btnConsultarTDD.setText("CONSULTAR SALDO");
        btnConsultarTDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTDDActionPerformed(evt);
            }
        });

        btnTranferirTDD.setText("TRANFERIR");
        btnTranferirTDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranferirTDDActionPerformed(evt);
            }
        });

        btnRetirarTDD.setText("RETIRAR");
        btnRetirarTDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarTDDActionPerformed(evt);
            }
        });

        txtRetirar.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        txtRetirar.setText("0.00");

        jLabel1.setText("Tarjeta");

        txtTarjeta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTarjeta.setText("5062470100731644 ");

        jLabel2.setText("Id_Usuario");

        txtNip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNip.setText("1224");

        btnAsignarTDD.setText("ASIGNAR CUENTAS");
        btnAsignarTDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTDDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(txtNip)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 340, Short.MAX_VALUE)
                        .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(internal_cajero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTranferirTDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRetirarTDD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarTDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCambiarDetallesTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignarTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(internal_cajero, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAsignarTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarDetallesTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnConsultarTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTranferirTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(btnRetirarTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCambiarDetallesTDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarDetallesTDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarDetallesTDDActionPerformed

    private void btnConsultarTDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTDDActionPerformed
     consultarSaldoTDD();
    }//GEN-LAST:event_btnConsultarTDDActionPerformed

    private void btnAsignarTDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarTDDActionPerformed

    private void btnRetirarTDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarTDDActionPerformed
      retirarTDD();
    }//GEN-LAST:event_btnRetirarTDDActionPerformed

    private void btnTranferirTDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranferirTDDActionPerformed
     DepositarTDD();
    }//GEN-LAST:event_btnTranferirTDDActionPerformed
     
    static {
        try {
            disableSslVerification();
        } catch (KeyManagementException ex) {
            Logger.getLogger(menuC.class.getName()).log(Level.SEVERE, null, ex);
        }
}

private static void disableSslVerification() throws KeyManagementException {
    try
    {
        // Create a trust manager that does not validate certificate chains
        TrustManager[] trustAllCerts = new TrustManager[] {new X509TrustManager() {
            public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                return null;
            }
            public void checkClientTrusted(X509Certificate[] certs, String authType) {
            }
            public void checkServerTrusted(X509Certificate[] certs, String authType) {
            }
        }
        };

        // Install the all-trusting trust manager
        SSLContext sc = SSLContext.getInstance("SSL");
        sc.init(null, trustAllCerts, new java.security.SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

        // Create all-trusting host name verifier
        HostnameVerifier allHostsValid = (String hostname, SSLSession session) -> true;

        // Install the all-trusting host verifier
        HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid);
    } catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }
}
    
    
    
// TODO Auto-generated method stub } @Override public void checkServerTrusted(java.security.cert.X509Certificate[] paramArrayOfX509Certificate, String paramString) throws CertificateException { // TODO Auto-generated method stub } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarTDD;
    private javax.swing.JButton btnCambiarDetallesTDD;
    private javax.swing.JButton btnConsultarTDD;
    private javax.swing.JButton btnRetirarTDD;
    private javax.swing.JButton btnTranferirTDD;
    private javax.swing.JDesktopPane internal_cajero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtRetirar;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}
